apps/notice/models.py
from apps.app import db
from datetime import datetime
from flask_login import current_user

class Notice(db.Model):
    __tablename__ = "notices"
    
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    content = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)
    user_id = db.Column(db.String, db.ForeignKey("users.id"))
    user = db.relationship('User', backref=db.backref('notices', lazy=True))
    author = db.Column(db.String(100), nullable=False)


    def __init__(self, title, content, author):
        self.title = title
        self.content = content
        self.author = author
        self.user_id = current_user.id  

apps/notice/__init__.py
import apps.notice.models

apps/notice/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from apps.notice.form import NoticeForm
from apps.notice.models import Notice
from datetime import datetime
from flask_login import current_user
from apps.app import db


notice = Blueprint('notice', __name__, template_folder="templates")

@notice.route('/create', methods=['GET', 'POST'])
def create_notice():
    form = NoticeForm()
   
    if form.validate_on_submit():
        author = current_user.username if current_user.is_authenticated else "Anonymous"
        notice = Notice(
            title=form.title.data,
            author=author,
            content=form.content.data
        )
        db.session.add(notice)
        db.session.commit()
        return redirect(url_for('notice.notice_index'))
   
       
    return render_template('notice/create.html', title='새로운 공지사항 작성', form=form)

@notice.route('/index')
def notice_index():
    notices = Notice.query.all()
    user = current_user
    notices.reverse()  
    return render_template('notice/index.html', title='공지사항 일람', notices=notices, user=user)

@notice.route('/detail/<int:notice_id>')
def notice_detail(notice_id):
    notice = Notice.query.filter_by(id=notice_id).first()

    return render_template('notice/detail.html', notice=notice)


    
@notice.route('/edit/<int:notice_id>', methods=['GET', 'POST'])
def edit_notice(notice_id):
    notice = Notice.query.get(notice_id)
    form = NoticeForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            notice.title = form.title.data
            notice.content = form.content.data
            db.session.commit()
            return redirect(url_for('notice.notice_detail', notice_id=notice.id))
    elif request.method == 'GET':
        form.title.data = notice.title
        form.content.data = notice.content
    return render_template('notice/edit.html', title='공지사항 수정', form=form, notice=notice)

@notice.route('/delete/<int:notice_id>', methods=['GET'])
def delete_notice(notice_id):
    notice = Notice.query.get(notice_id)
    if notice:
        db.session.delete(notice)
        db.session.commit()
    else:
        flash('해당 공지사항을 찾을 수 없습니다.', 'error')
    return redirect(url_for('notice.notice_index'))

apps/notice/templates/notice/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8" />
    <title>휘리에스</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
</head>

<body>
    <!-- 내비게이션 바를 작성한다 -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('detector.index') }}">휘리에스 아샤</a>
            
            <!-- 이미지 검색 폼을 추가한다 -->
            
            <!-- 사용자 정보와 로그아웃 링크 -->
            <div class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                    <a class="nav-link" href="{{ url_for('notice.notice_index') }}">공지사항</a>
                    <a class="nav-link" href="{{ url_for('crud.users') }}">회원일람</a>
                    <a class="nav-link" href="{{ url_for('detector.dindex') }}">감지</a>
                    <span class="nav-item nav-link">{{ current_user.username }}</span>
                    <a href="{{ url_for('auth.logout') }}" class="nav-link">로그아웃</a>
                {% else %}
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">신규 등록</a>
                    <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
                {% endif %}
            </div>
        </div>
    </nav>

    <!-- block content를 section class="container"로 둘러싼다 -->
    <section class="container">
        {% block content %}{% endblock %}
    </section>

    <script>
         function submit_go(){
            form = document.querySelector("form[name='dtSearchForm']");
            if(!form.search.value){
                alert("검색 태그를 입력하세요.");
                return false;
            }
            form.submit();
        }
    </script>
</body>

</html>

apps/notice/templates/notice/create.html
{% extends "notice/base.html" %}
{% block title %}공지사항 일람{% endblock %}
{% block content %}



<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8" />
    <title>새로운 공지사항 작성</title>
</head>

    <body>
        <div class="card card-info">
            <div class="card-header">
                <h3 class="card-title"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">공지사항 작성</font></font></h3>
            </div>
            <form class="form-horizontal" action="{{ url_for('notice.create_notice') }}" method="POST" novalidate="novalidate">
                {{ form.csrf_token }}
                <div class="card-body">
                    <div class="form-group row">
                        <label for="title" class="col-sm-2 col-form-label"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">제목</font></font></label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="title" name="title" placeholder="제목">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="author" class="col-sm-2 col-form-label"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">작성자</font></font></label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="author" name="author" placeholder="작성자" value="{{ current_user.username }}" readonly>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="content" class="col-sm-2 col-form-label"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">내용</font></font></label>
                        <div class="col-sm-10">
                            <textarea class="form-control" id="content" name="content" rows="5" placeholder="내용"></textarea>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-info"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">공지 등록</font></font></button>
                    <a href="{{ url_for('notice.notice_index') }}" class="btn btn-info"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">취소</font></font></a>
            </form>
        </div>
    </body>
    

</html>




{% endblock %}

apps/notice/templates/notice/detail.html
{% extends "notice/base.html" %}
{% block title %}공지사항 상세 내용{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card mt-5">
                <div class="card-header">
                    <h3 class="card-title">공지사항</h3>
                </div>
                <div class="card-body">
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <th class="table-dark" style="width: 20%;">제목</th>
                                <td>{{ notice.title }}</td>
                            </tr>
                            <tr>
                                <th class="table-dark">작성자</th>
                                <td>{{ notice.author }}</td>
                            </tr>
                            <tr>
                                <th class="table-dark">작성일</th>
                                <td>{{ notice.created_at.strftime("%Y.%m.%d %H:%M") }}</td>
                            </tr>
                            <tr>
                                <th class="table-dark">내용</th>
                                <td><textarea disabled rows="10" class="form-control bg-white" style="resize: none;">{{ notice.content }}</textarea></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <a href="{{ url_for('notice.edit_notice', notice_id=notice.id) }}" class="btn btn-primary">수정</a>
                    <a href="{{ url_for('notice.notice_index')}}" class="btn btn-secondary">돌아가기</a>
                    <!-- 삭제 버튼 추가 -->
                    <form action="{{ url_for('notice.delete_notice', notice_id=notice.id) }}" method="get" style="display: inline;">
                        <button type="submit" class="btn btn-danger">삭제</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

apps/notice/templates/notice/edit.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8"/>
    <title>공지사항 편집</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
</head>

<body>
    {% extends "notice/base.html" %}
    {% block title %}공지사항 편집{% endblock %}
    {% block content %}    
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">공지사항 편집</font></font></h3>
        </div>
        <!-- /.card-header -->
        <form action="{{ url_for('notice.edit_notice', notice_id=notice.id) }}" method="POST" novalidate="novalidate">
            {{ form.csrf_token }}
            <div class="card-body">
                <div class="form-group row">
                    <label for="title" class="col-sm-2 col-form-label"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">제목</font></font></label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="title" name="title" placeholder="제목" value="{{ notice.title }}">
                    </div>
                </div>
                {% for error in form.title.errors %}
                <span style="color: red;">{{ error }}</span>
                {% endfor %}
                <div class="form-group row">
                    <label for="author" class="col-sm-2 col-form-label"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">작성자</font></font></label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="author" name="author" placeholder="작성자명" value="{{ notice.author }}">
                    </div>
                </div>
                {% for error in form.author.errors %}
                <span style="color: red;">{{ error }}</span>
                {% endfor %}
                <div class="form-group row">
                    <label for="content" class="col-sm-2 col-form-label"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">내용</font></font></label>
                    <div class="col-sm-10">
                        <textarea class="form-control" id="content" name="content" rows="5" placeholder="내용">{{ notice.content }}</textarea>
                    </div>
                </div>
                {% for error in form.content.errors %}
                <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-info"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">수정</font></font></button>
                <a href="{{ url_for('notice.notice_detail', notice_id=notice.id) }}" class="btn btn-info"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">돌아가기</font></font></a>
            </div>
            <!-- /.card-footer -->
        </form>
    </div>
    {% endblock %}
</body>
</html>

apps/notice/templates/notice/index.html
{% extends "notice/base.html" %}
{% block title %}공지사항 일람{% endblock %}
{% block content %}

<div class="col-12">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">공지사항</h3>

          
      </div>
      <div class="card-body table-responsive p-0">
        <table class="table table-hover text-nowrap">
          <thead>
            <tr>
              <th>순번</th>
              <th>제목</th>
              <th>작성자명</th>
              <th>날짜</th>           
            </tr>
          </thead>
          <tbody>
            {% for notice in notices %}
            <tr>
                <td><a href="{{ url_for('notice.notice_detail', notice_id=notice.id) }}">{{ notice.id }}</a></td>
                <td>{{ notice.title }}</td>
                <td>{{ notice.author }}</td>
                <td>{{ notice.created_at.strftime("%Y.%m.%d") }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <a href="{{ url_for('notice.create_notice') }}"><input type="submit" value="작성"></a>
      </div>
    </div>
  </div>
  

{% endblock %}

