apps/crud/models.py
from datetime import datetime

from apps.app import db, login_manager
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash


# db.Model을 상속한 User 클래스를 작성한다
class User(db.Model, UserMixin):
    # 테이블명을 지정한다
    __tablename__ = "users"
    # 컬럼을 정의한다
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, index=True)
    email = db.Column(db.String, unique=True, index=True)
    password_hash = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)


    # backref를 이용하여 relation 정보를 설정한다
    user_images = db.relationship("UserImage", backref="user",order_by="desc(UserImage.id)")
    
    # 비밀번호를 세트하기 위한 프로퍼티
    @property
    def password(self):
        raise AttributeError("읽어 들일 수 없음")

    # 비밀번호를 세트하기 위한 센터 함수로 해시화한 비밀번호를 세트한다
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    # 비밀번호 체크를 한다
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    # 메일 주소 중복 체크를 한다
    def is_duplicate_email(self):
        return User.query.filter_by(email=self.email).first() is not None


# 로그인하고 있는 사용자 정보를 취득하는 함수를 작성한다
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, length, InputRequired
from wtforms import HiddenField

# 사용자 신규 작성과 사용자 편집 폼 클래스
class UserForm(FlaskForm):
    # 사용자 폼의 username 속성의 라벨과 벨리데이터를 설정한다
    username = StringField(
        "사용자명",
        validators=[
            DataRequired(message="사용자명은 필수입니다."),
            length(max=30, message="30문자 이내로 입력해 주세요."),
        ],
    )

    # 사용자폼 email 속성의 라벨과 밸리테이터를 설정한다
    email = StringField(
        "메일 주소",
        validators=[
            DataRequired(message="메일 주소는 필수입니다."),
            Email(message="메일 주소의 형식으로 입력해 주세요."),
        ],
    )

    # 사용자 폼 password 속성의 라벨과 벨리데이터를 설정한다
    password = PasswordField("비밀번호", validators=[DataRequired(message="비밀번호는 필수입니다.")])

    # 사용자폼 submit의 문구를 설정한다
    submit = SubmitField("신규 등록")

class PasswordCheckForm(FlaskForm):
    user_id = HiddenField('user_id', validators=[InputRequired()])
    password = PasswordField('password', validators=[InputRequired()])

apps/crud/__init__.py
import apps.crud.models

apps/crud/views.py
from apps.app import db
from apps.crud.models import User
from apps.crud.forms import UserForm

from werkzeug.security import check_password_hash

from flask import Blueprint,render_template, redirect, url_for, request, flash

from flask_login import login_required



# Blueprint로 crud 앱을 생성한다
crud = Blueprint(
    "crud",
    __name__,
    template_folder="templates",
    static_folder="static",
)




# index 엔드포인트를 작성하고 index.html을 반환한다
@crud.route("/")
@login_required
def index():
    return render_template("crud/index.html")


@crud.route("/sql")
@login_required
def sql():
    #SELECT
    user = db.session.query(User).filter_by(id=1).all()
    print(user)
    
    # user=User(
    #     username="사용자명",
    #     email="flaskbook@example.com",
    #     password="비밀번호"
    # )
    #db.session.add(user)
    #db.session.commit()
    
    #UPDATE
    # user = db.session.query(User).filter_by(id=1).first()
    # #print(user.email)
    # user.username="사용자명2"
    # user.email="flaskbook2@name.com"
    # user.password="12233445"
    
    # db.session.add(user)
    # db.session.commit()
    
    
    #Delete
    # user=db.session.query(User).filter_by(id=1).delete()
    # db.session.commit()
    
    
    return "콘솔 로그를 확인해 주세요"

@crud.route("/users/new", methods=["GET", "POST"])
@login_required
def create_user():
    # UserForm을 인스턴스화한다
    form = UserForm()

    # 폼의 값을 벨리데이트한다
    if form.validate_on_submit():
        # 사용자를 작성한다
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
        )

        # 사용자를 추가하고 커밋한다
        db.session.add(user)
        db.session.commit()

        # 사용자의 일람 화면으로 리다이렉트한다
        return redirect(url_for("crud.users"))
    #return render_template("crud/create.html", form=form)
    return render_template("crud/create_html.html", form=form)


@crud.route("/users/new/html", methods=["GET","POST"])
@login_required
def create_user_html():
    
    if request.method == "POST":
        user = User(
            #queryString : ?key=value&key=value.......
            
            #username=request.args.get("username"),
            #email=request.args.get("email"),
            #password=request.args.get("password")
            
            #<form> 입력
            username = request.form["username"],
            email = request.form["email"],
            password = request.form["password"]
        )    
        
        # 사용자를 추가하고 커밋한다
        print("username : ",user.username)
        print("email : ",user.email)
        print("password : ",user.password_hash)
        
        db.session.add(user)
        db.session.commit()
        
        return redirect(url_for("crud.users"))
    
    return render_template("crud/create_html.html")

@crud.route("/users")
@login_required
def users():
    users = User.query.all()
    return render_template("crud/index.html", users=users)


# methods에 GET과 POST를 지정한다
@crud.route("/users/<user_id>", methods=["GET", "POST"])
@login_required
def edit_user(user_id):
    form = UserForm()
    # User 모델을 이용하여 사용자를 취득한다
    user = User.query.filter_by(id=user_id).first()
    
    if request.method == "POST":
        
        #insert user
        # user = User(
        #     username = request.form["username"], 
        #     password = request.form["password"],
        #     email = request.form["email"]
        # )

        #update
        user.username = request.form["username"]
        user.email = request.form["email"]
        user.password = request.form["password"]
        
        db.session.add(user)
        db.session.commit()
        
        return redirect(url_for("crud.users"))
        
    # GET의 경우는 HTML을 반환한다
    return render_template("crud/edit_html.html", user=user, form=form)




#패스워드 변경
from flask import render_template, flash, redirect, url_for, request
from apps.crud.forms import PasswordCheckForm  # 모듈 import 변경

@crud.route("/pwd_check", methods=["GET", "POST"])
@login_required
def pwd_check():
    id = request.args.get("id")
    form = PasswordCheckForm(user_id=id)  # PasswordCheckForm 사용 변경

    if form.validate_on_submit():
        user_id = form.user_id.data
        password = form.password.data

        user = db.session.query(User).filter_by(id=user_id).first()

        if user and check_password_hash(user.password_hash, password):
            return render_template("crud/pwd_change.html")
        else:
            flash("패스워드가 일치하지 않습니다.")

    return render_template("crud/pwd_check.html", form=form, id=id)

@crud.route("/users/<user_id>/delete", methods=["POST"])
@login_required
def delete_user(user_id):
    user = User.query.filter_by(id=user_id).first()
    if user:
        db.session.delete(user)
        db.session.commit()
    else:
        flash('해당 유저를 찾을 수 없습니다.','error')
    return redirect(url_for('crud.users'))

apps/crud/templates/crud/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8" />
    <title>휘리에스</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
</head>

<body>
    <!-- 내비게이션 바를 작성한다 -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('detector.index') }}">휘리에스 아샤</a>
            
            <!-- 이미지 검색 폼을 추가한다 -->
            
            
            <!-- 사용자 정보와 로그아웃 링크 -->
            <div class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                    <a class="nav-link" href="{{ url_for('notice.notice_index') }}">공지사항</a>
                    <a class="nav-link" href="{{ url_for('crud.users') }}">회원일람</a>
                    <a class="nav-link" href="{{ url_for('detector.dindex') }}">감지</a>
                    <span class="nav-item nav-link">{{ current_user.username }}</span>
                    <a href="{{ url_for('auth.logout') }}" class="nav-link">로그아웃</a>
                {% else %}
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">신규 등록</a>
                    <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
                {% endif %}
            </div>
        </div>
    </nav>

    <!-- block content를 section class="container"로 둘러싼다 -->
    <section class="container">
        {% block content %}{% endblock %}
    </section>

    <script>
         function submit_go(){
            form = document.querySelector("form[name='dtSearchForm']");
            if(!form.search.value){
                alert("검색 태그를 입력하세요.");
                return false;
            }
            form.submit();
        }
    </script>
</body>

</html>

apps/crud/templates/crud/create_html.html
{% extends "crud/base.html" %}
{% block title %}사용자 신규 작성{% endblock %}
{% block content %}

<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8" />
    <title>사용자 신규 등록</title>
</head>

<body>
    <div class="card-body register-card-body">
        <form action="/crud/users/new/html" method="POST" role="form" onsubmit="return user_regist_go();">
            {{ form.csrf_token }}
            <div class="input-group mb-3">
                <input type="text" class="form-control" id="username" name="username" placeholder="사용자명" value=""/>
            </div>
            <div class="input-group mb-3">
                <input type="email" class="form-control" id="email" name="email" placeholder="메일 주소" value=""/>
            </div>
            <div class="input-group mb-3">
                <input type="password" class="form-control" id="password" name="password" placeholder="비밀번호" value=""/>
            </div>
            <div class="input-group mb-3">
                <input type="submit" id="submit" name="submit" class="btn btn-primary btn-block" value="신규 등록">
            </div>
        </form>
    </div>
</body>
<script>
var vali_message={
    username : {
        none : "사용자명은 필수입니다.",
        length : "30문자 이내로 입력해 주세요."
    },
    email : {
        none : "메일 주소는 필수입니다.",
        regex : "메일 주소의 형식으로 입력해 주세요."
    }, 
    password : {
        none : "비밀번호는 필수입니다."
    }

}
function user_regist_go(){
   
    for (var div of document.querySelectorAll('div.vali')){ div.remove();}
    var submit_ok = true;
    form =document.querySelector("form[role='form']");
    
    for (var element of form){
        //alert(element.name);
        if(!element.value){
            make_message_span(element,vali_message[element.name].none);
            submit_ok = false;
            continue;
        }


        switch(element.name){
            case "username":
                if(element.value.length > 30){ 
                    make_message_span(element,vali_message[element.name].length);
                    submit_ok = false;
                }
            break;
            case "email":
                let regexp = /[a-z0-9]+@[a-z]+\.[a-z]{2,3}/g;
                if(!element.value.match(regexp)){ 
                    make_message_span(element,vali_message[element.name].regex);
                    submit_ok = false;
                }
            break;
        }
        
    }
    return submit_ok;
}

function make_message_span(target, message){
    let div = document.createElement('div');
    div.classList.add("vali")

    let span = document.createElement('span');
    span.style.color='red';
    span.innerHTML = message;

    div.append(span);
    
    target.after(div);
    
}
</script>

</html>
{% endblock %}

apps/crud/templates/crud/edit_html.html
{% extends "crud/base.html" %}
{% block title %}사용자 편집{% endblock %}
{% block content %}

<h2>사용자 편집</h2>
<form id="user-edit-form" action="/crud/users/{{ user.id }}" method="POST" role="form" onsubmit="return user_edit_go();">
    {{ form.csrf_token }}
    <div class="card-body register-card-body">
        <div class="input-group mb-3">
            <input type="text" class="form-control" id="username" name="username" placeholder="사용자명" value="{{ user.username }}">
        </div>
        <div class="input-group mb-3">
            <input type="email" class="form-control" id="email" name="email" placeholder="메일 주소" value="{{ user.email }}">
        </div>
        <div class="input-group mb-3" onclick="OpenWindow('/crud/pwd_check?id={{ user.id }}','비밀번호변경','500','200');">
            <input type="password" class="form-control" id="password" name="password" placeholder="비밀번호" value="" readonly>
        </div>
        <div class="row">
            <div class="col-md-4">
                <button type="submit" id="submit" name="submit" class="btn btn-primary btn-block" value="갱신" onclick="return validatePassword();">갱신</button>
            </div>
            <div class="col-md-4">
                <a href="{{ url_for('crud.users')}}" class="btn btn-secondary btn-block">돌아가기</a>
            </div>
            <div class="col-md-4">
                <button type="button" class="btn btn-danger btn-block" value="삭제" onclick="delete_go();">삭제</button>              
            </div>
        </div>
    </div>
</form>


<form id="delete-form" action="{{ url_for('crud.delete_user', user_id=user.id) }}" method="post">
    {{ form.csrf_token }}
</form>

<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="{{ url_for('crud.static', filename='common.js') }}"></script>
<script src="{{ url_for('crud.static', filename='user_edit.min.js') }}"></script>

<script>
    function validatePassword() {
        var passwordField = document.getElementById('password');
        if (passwordField.value === '') {
            alert('비밀번호를 입력하세요.');
            return false;
        }
        return true;
    }

    function delete_go(){
        if (confirm('정말로 삭제하시겠습니까?')){
            document.querySelector("form#delete-form").submit()
        }
        return false;
    }
</script>

{% endblock %}

apps/crud/templates/crud/index.html
{% extends "crud/base.html" %}
{% block title %}사용자 일람{% endblock %}
{% block content %}

<div class="col-12">
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">사용자 일람</h3>
    </div>
    <div class="card-body table-responsive p-0">
      <table class="table table-hover text-nowrap">
        <thead>
          <tr>
            <th>사용자 ID</th>
            <th>사용자명</th>
            <th>메일 주소</th>    
          </tr>
        </thead>
        <tbody>
          {% for user in users %}
          <tr>
            <td><a href="{{ url_for('crud.edit_user', user_id=user.id)}}">{{user.id}}</a></td>
            <td>{{ user.username }}</td>
            <td>{{ user.email }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
      <a href="{{ url_for('crud.create_user') }}"><input type="submit" value="신규 등록"></a>
    </div>
  </div>
</div>

{% endblock %}

apps/crud/templates/crud/pwd_change.html
{% block title %}비밀번호 변경{% endblock %}
{% block content %}
        <form role="form">
            <label for="password">
                새로운 비밀번호 
            </label>
            <input type="password" id="password" name="password" />
            <br/>
            <label for="chk_password">
                비밀번호 확인
            </label>
            <input type="password" id="chk_password" name="chk_password" />
        </form>
        <button type="button" onclick="change_pwd();">확인</button>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script>
        function change_pwd(){

            let form = $('form[role="form"]'); 

            for (var element of form[0]){
                if(!element.value) {
                    alert("패스워드를 입력하세요.");
                    $(element).focus();
                    return;}
            }
            if(form[0].password.value == form[0].chk_password.value){
                window.close();
                window.opener.setPassword=form[0].password.value;
                window.opener.input_password();
            }else{
                alert("패스워드가 일치하지 않습니다.");
            }
        }
    </script>
{% endblock %}

apps/crud/templates/crud/pwd_check.html
{% block title %}비밀번호 확인{% endblock %}
{% block content %}
<form method="POST" role="form" >
    {{ form.csrf_token }}
    <input type="hidden" name="user_id" value="{{id}}" />
    <label for="pwd_input" >현재 패스워드</label>
    <input type="password" name="password" />
    <input type="submit" value="전송">
</form>

{%with messages = get_flashed_messages()%}
    {% for message in messages%}
        <script>
            alert("{{message}}");
        </script>
    {% endfor %}
{% endwith %}

{% endblock %}